# Generated by Django 5.0.6 on 2024-05-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_registration_enable_attendance_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='Average',
            new_name='average',
        ),
    ]
